### ISSUE TITLE
Add support for ROS2 Humble

### ISSUE THREAD

**Issue by cco-seasony** [splintered-reality/py_trees_ros#174]
Hey!
Do you have any intentions on doing a release for ROS2 Galactic.

Thanks in advance!

**Comment by stonier** [comment]
Aye, I do plan to. Moved house and bought another recently, so development hit a bit of a speed bump.

I'll probably upgrade to `py_trees 2.2` in the process. There's a couple of api changes needed.

Did you have try building from source? Any problems I should take note of?

**Comment by cco-seasony** [comment]
@stonier Hey! sorry for the delay. We just moved from foxy to galactic and have not had the chance to build from source and test py tree.
We have some other things on the backlog before starting any testing with py tree. But I will let you know if we do so :D In the mean time I will keep track of your progress in case you upgrade before I build from source.

**Comment by goekce** [comment]
I compiled the following repos from source on Galactic:
```
py_trees  py_trees_js  py_trees_ros  py_trees_ros_interfaces  py_trees_ros_tutorials  py_trees_ros_viewer
```

To test it I ran the tutorial `tutorial_two_battery_check_launch.py` but got an API-related error:

```
... configuration_group_box.py", line 58, in set_charging_status
[mock-dashboard-2]     self.ui.battery_charging_check_box.setChecked(charging_status)
[mock-dashboard-2] TypeError: setChecked(self, bool): argument 1 has unexpected type 'float'
```
Other nodes continued executing. I am new to `py_trees` so I am still not sure if `py_trees` can be used in Galactic.

**Comment by jkeshav-bvignesh** [comment]
Hey @stonier, do you still plan to add ROS2 Galactic & Humble support? 
I assume that a colcon build from source won't fully work since you mentioned that a few api changes are required.

**Comment by stonier** [comment]
Just started looking at it, ran into some speed bumps with rhel too. Probably going to need upgrade testing from nose to tox.

**Comment by stonier** [comment]
Finally, underway. Tracking the effort for `py_trees` here: https://github.com/splintered-reality/py_trees/milestone/14. Will do similarly for `py_trees_ros` when done there.

A colcon build using the foxy release branches should still work on at least galactic - it's bloom that is having a problem. If there's a problem with colcon, let me know and I'll see if I can backport some fixes to make those release branches compatible across ros distros.

**Comment by jkeshav-bvignesh** [comment]
This is great! Thanks!

> A colcon build using the foxy release branches should still work on at least galactic

This is exactly what I have been doing this week for Galactic. Haven't faced any issue so far but I wasn't sure if the whole framework can be used as is. Thanks for the clarification!

**Comment by jodusan** [comment]
@stonier  hey, is galactic & humble support coming? Thanks!

**Comment by stonier** [comment]
> I compiled the following repos from source on Galactic:
> 
> ```
> py_trees  py_trees_js  py_trees_ros  py_trees_ros_interfaces  py_trees_ros_tutorials  py_trees_ros_viewer
> ```
> 
> To test it I ran the tutorial `tutorial_two_battery_check_launch.py` but got an API-related error:
> 
> ```
> ... configuration_group_box.py", line 58, in set_charging_status
> [mock-dashboard-2]     self.ui.battery_charging_check_box.setChecked(charging_status)
> [mock-dashboard-2] TypeError: setChecked(self, bool): argument 1 has unexpected type 'float'
> ```
> 
> Other nodes continued executing. I am new to `py_trees` so I am still not sure if `py_trees` can be used in Galactic.

Fixed in https://github.com/splintered-reality/py_trees_ros_tutorials/pull/47. There was a hidden bug present in the tutorial only.

**Comment by stonier** [comment]
A meta-list for Humble

## Bugfixes

**py_trees_ros_tutorials**
* [x] https://github.com/splintered-reality/py_trees_ros_tutorials/pull/47

## New Features

## General Improvements

**py_trees_ros**

* #187 (eliminates warning messages)

**Development Environment**

See the README's in [py_trees](https://github.com/splintered-reality/py_trees/tree/devel/.devcontainer) and [py_trees_ros](https://github.com/splintered-reality/py_trees_ros/tree/devel/.devcontainer) for more info.

* [x] #183 (for foxy)
* [x] #187 (upgraded for humble)

**Comment by stonier** [comment]
Humble / Rolling task list &rarr; #195.
