### ISSUE TITLE
Installation for ROS-1

### ISSUE THREAD

**Issue by gdaddi** [splintered-reality/py_trees_ros#179]
Hi,

From the documentation, I am having trouble understanding what's the most straightforward way to install py-trees-ros for ROS Noetic. Does anyone have any suggestions? I tried using `sudo apt install ros-noetic-py-trees`, but that does not seem to install almost anything.

Thanks

**Comment by stonier** [comment]
http://repositories.ros.org/status_page/ros_noetic_default.html?q=py_trees

**Comment by stonier** [comment]
`sudo apt install ros-noetic-py-trees-ros ros-noetic-rqt-py-trees` should get them all.

**Comment by gdaddi** [comment]
thank you, that worked.
