### ISSUE TITLE
Setup with kwargs, just as in py_trees

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros#211]
**Problem**

Kwarg support for setup went into py_trees with https://github.com/splintered-reality/py_trees/commit/20859f21a65232af869540f025573b50122c1ba3.

It didn't propogate through to the ros tree use case.

**Proposed Action**

Propogate that functionality to the ros tree manager.

**Other Notes**

ROS behaviours configure themselves from the ros1/ros2 param server. Ostensibly you could have a ROS tree with many non-ros behaviours that need configuring at setup, so this ought to be a valid use case to support.

Question originally raised in #209.

**Comment by haudren-woven** [comment]
Thank you, this looks great!

**Comment by stonier** [comment]
Resolved by #212.
