### ISSUE TITLE
Error when running the tutorials installed from the ROS repo

### ISSUE THREAD

**Issue by jr-bor** [splintered-reality/py_trees_ros#26]
When installing the py_trees suite from the ROS repo and going through the tutorials I get the error:
```
ERROR: cannot launch node of type [py_trees_ros/mock_safety_sensors]: can't locate node [mock_safety_sensors] in package [py_trees_ros]
```
Fixed by #25 . Until pushed to the ROS repo the script can be manually put in:
> /opt/ros/kinetic/lib/py_trees_ros

and give it execution permission

**Comment by stonier** [comment]
PR #25 is in.
