### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by veimox** [splintered-reality/py_trees_ros#40]
@naveedhd @stonier 

`py_trees` is released for melodic but `py_trees_ros`, `py_trees_msgs` and `rqt_py_trees` [are not](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L2721).

I tried to create a workspace with these four and rosdep failed to find the `python-termcolor` package. This definition [was added](https://github.com/ros/rosdistro/pull/18809) and now it resolves correctly. Packages compile but I have not run any tests.

I was wondering what is the roadmap for these packages to be released in melodic. We could do a checklist and split resources :smile:

**Comment by stonier** [comment]
[Build Farm Status (py_trees)](http://repositories.ros.org/status_page/ros_melodic_default.html?q=py_trees)

* [x] py_trees 0.6.1 
* [x] py_trees_msgs 0.3.5
* [x] py_trees_ros 0.5.14
* [x] rqt_py_trees 0.3.0

**Comment by stonier** [comment]
@veimox can I lean on you for some melodic information (I don't have a pc with artful/bionic yet)? Trying to bloom this repo I get an error failing to find `python-termcolor`:

```
Pre-verifying Debian dependency keys...
Running 'rosdep update'...
Could not resolve rosdep key 'python-termcolor' for distro 'bionic':
No definition of [python-termcolor] for OS version [bionic]
        rosdep key : python-termcolor
        OS name    : ubuntu
        OS version : bionic
        Data: debian:
  buster:
  - python-termcolor
  jessie:
  - python-termcolor
  stretch:
  - python-termcolor
  wheezy:
    pip:
      packages:
      - termcolor
fedora:
- python-termcolor
gentoo:
- dev-python/termcolor
osx:
  pip:
    packages:
    - termcolor
ubuntu:
  '*':
  - python-termcolor
  artful_python3:
  - python3-termcolor
  bionic_python3:
  - python3-termcolor
  cosmic_python3:
  - python3-termcolor
  trusty_python3:
  - python3-termcolor
  xenial_python3:
  - python3-termcolor
  zesty_python3:
  - python3-termcolor

Failed to resolve python-termcolor on ubuntu:bionic with: Error running generator: Failed to resolve rosdep key 'python-termcolor', aborting.
python-termcolor is depended on by these packages: ['py_trees_ros']
<== Failed
```

That's a little baffling - especially as the key/value pairs all look correct. Manuallly running

```
rosdep --os=ubuntu:bionic resolve python-termcolor
```

does indeed produce the above output. Do you get the same in your source workspace?

**Comment by stonier** [comment]
Aha, I had an old rosdep that didn't support the wild card '*'.

**Comment by stonier** [comment]
Everything on it's way so you should find them in the shadow repository this week.

Closing in advance so I don't have to return on the assumption that everything goes to plan :)

Will re-open if there are problems.
