### ISSUE TITLE
Resolve kinetic-melodic branches

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros#62]
Really ought to have put them on the same `release/0.5.x` branch back when. They now seem to have gotten out of sync (I'd stopped working on kinetic, but turns out there are quite a few users still).

**Comment by stonier** [comment]
* [kinetic<-melodic](https://github.com/stonier/py_trees_ros/compare/release/0.5-kinetic...release/0.5-melodic?expand=1) : has quite a few new features
* [melodic<-kinetic](https://github.com/stonier/py_trees_ros/compare/release/0.5-melodic...release/0.5-kinetic?expand=1) - just catching up on removing the print and 0.5.17 version

**Comment by naveedhd** [comment]
Is there any signifant differences between melodic/kinetic? meaning can they be maintained as one?

I can start tracking kinetic (cause this is what we use) and start pulling it up to melodic (and later to crystal atleast in terms of features and idioms)

**Comment by stonier** [comment]
It is perhaps possible. 

0.5->0.6 was dictated by a big push to make it python2/3 compatible (python2 got dropped later, 0.8 I think), but glancing at the changelog, 0.5->0.6 does not look like it introduced breaking functionality.

If you'd like to test 0.6 (melodic) sources on kinetic and they work out for you, we can get kinetic and melodic both on 0.6. I don't have a machine around to test on kinetic any longer.

Backporting everything that's gone into crystal - that's significantly more work and much might not be possible if it breaks the api promise.

**Comment by stonier** [comment]
Scratch above. I was staring at `py_trees` versions (kinetic: 0.5.x melodic: 0.6.x).

For `py_trees_ros` it should be fine .... They are both `0.5.x`. I'll move on this shortly.

**Comment by stonier** [comment]
Both using the [release/0.5.x](https://github.com/splintered-reality/py_trees_ros/tree/release/0.5.x) branch now, new debs for both distros will be `v0.5.18`.

The previous release branches are still around in case we run into trouble but have been renamed [graveyard/0.5-kinetic](https://github.com/splintered-reality/py_trees_ros/tree/graveyard/0.5-kinetic) and [graveyard/0.5-melodic](https://github.com/splintered-reality/py_trees_ros/tree/graveyard/0.5-melodic). See also this [diff](https://github.com/splintered-reality/py_trees_ros/compare/graveyard/0.5-kinetic...graveyard/0.5-melodic) of melodic vs kinetic. 

Reopen if you discover any issues.
